import type {Metadata} from "next";
import {Manrope} from "next/font/google";
import "./globals.css";
import React from "react";
import {StoreProvider} from "@/Redux/StoreProvider";
import ReactQueryProvider from "@/ReactQueryProvider";

const manrope = Manrope({
    weight: ['400', "600", "300", "500",],
    subsets: ['latin'],
    display: 'swap',
})


export const metadata: Metadata = {
    title: "Личный кабинет Агента",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <StoreProvider>
            <ReactQueryProvider>
                <html lang="ru">
                <body className={ manrope.className }>
                { children }
                </body>
                </html>
            </ReactQueryProvider>
        </StoreProvider>
    );
}
