import type {Metadata} from "next";
import {Manrope} from "next/font/google";
import "./globals.css";
import React from "react";
import {StoreProvider} from "@/Redux/StoreProvider";
import ReactQueryProvider from "@/ReactQueryProvider";
import Header from "@/components/Header/Header";

const manrope = Manrope({
    weight: ['400', "600", "300", "500",],
    subsets: ['latin'],
    display: 'swap',
})


export const metadata: Metadata = {
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <StoreProvider>
            <ReactQueryProvider>
                <html lang="en">
                <head>
                    <meta httpEquiv="Content-Security-Policy" content="upgrade-insecure-requests"/>
                    <title>ЛК Агента</title>
                </head>
                <body className={ manrope.className }>
                <Header/>
                <main className='mt-4 sm:mt-10'>
                    { children }
                </main>
                </body>
                </html>
            </ReactQueryProvider>
        </StoreProvider>
);
}
